#!/usr/bin/env pwsh
# PowerShell parity of example-action.sh.

param(
    [switch]$Auto,
    [switch]$DryRun,
    [string]$Answers,
    [switch]$Help,
    [Parameter(Position = 0)][string]$Topic = 'example-topic'
)

$ErrorActionPreference = 'Stop'
$ScriptDir = Split-Path -Parent $PSCommandPath
. (Join-Path $ScriptDir 'common.ps1')

if ($Auto)    { $env:KISS_AUTO = '1' }
if ($DryRun)  { $env:KISS_DRY_RUN = '1' }
if ($Answers) {
    $env:KISS_ANSWERS = $Answers
    Import-KissAnswers -Path $Answers
}

if ($Help) {
    @'
Usage: example-action.ps1 [-Auto] [-Answers FILE] [-DryRun] [-Help] [Topic]

Drafts an example artefact at docs/<work-type>/example.md to demonstrate
the shared common.ps1 helpers. Copy this script and rename it when
building a real skill action.

Parameters:
  -Auto             Non-interactive; resolve answers from env/answers/extracts
  -Answers FILE     KEY=VALUE file consulted when -Auto
  -DryRun           Print what would be written, do not touch the filesystem
  -Help             Show this message and exit
'@ | Write-Host
    exit 0
}

$ctx = Read-Context

$OutputFormat = Resolve-Auto -Key 'KISS_OUTPUT_FORMAT' -Default 'markdown'

if ($env:KISS_DRY_RUN -eq '1') {
    $OutFile = Join-Path `
        (Join-Path (Join-Path $ctx.REPO_ROOT $ctx.DOCS_DIR) '_template-output') `
        'example.md'
    Write-Host ("[dry-run] would write: {0}" -f $OutFile)
    Write-Host ("[dry-run] topic:       {0}" -f $Topic)
    Write-Host ("[dry-run] format:      {0}" -f $OutputFormat)
    exit 0
}

$OutDir  = Get-WorktypeDir -Name '_template-output'
$OutFile = Join-Path $OutDir 'example.md'

if (-not (Confirm-BeforeWrite -Message "Write example artefact to $OutFile.")) {
    Write-Error 'Aborted.'
    exit 1
}

$body = @"
# Example artefact — $Topic

This file was generated by ``agent-skills/_template/scripts/powershell/example-action.ps1``
as a demonstration of the shared helper library.

- Repo root:        $($ctx.REPO_ROOT)
- Docs root:        $($ctx.DOCS_DIR)
- Current feature:  $(if ($ctx.CURRENT_FEATURE) { $ctx.CURRENT_FEATURE } else { '<none>' })
- Output format:    $OutputFormat
"@
Set-Content -LiteralPath $OutFile -Value $body

Write-Extract -ArtefactPath $OutFile `
    "TOPIC=$Topic" `
    "OUTPUT_FORMAT=$OutputFormat" | Out-Null

Write-Host ("Wrote {0}" -f $OutFile)
