#!/usr/bin/env bash
# Sample action script for a role skill.
#
# Replace the body of this script with the real work the new skill
# performs. The scaffolding at the top (source common.sh, parse std
# args, read context) is identical for every skill — keep it.

set -e

SCRIPT_DIR="$(CDPATH="" cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=common.sh
source "$SCRIPT_DIR/common.sh"

kiss_parse_standard_args "$@"
set -- "${KISS_REST_ARGS[@]}"

if [ "${1:-}" = "--help" ]; then
    cat <<'USAGE'
Usage: example-action.sh [--auto] [--answers FILE] [--dry-run] [--help] [topic]

Drafts an example artefact at docs/<work-type>/example.md to demonstrate
the shared common.sh helpers. Copy this script and rename it when
building a real skill action.

Flags:
  --auto            non-interactive; resolve answers from env/answers/extracts
  --answers FILE    KEY=VALUE file consulted when --auto
  --dry-run         print what would be written, do not touch the filesystem
  --help            show this message and exit
USAGE
    exit 0
fi

read_context

TOPIC="${1:-example-topic}"

# Example: resolve an answer key with the --auto chain. The default
# "kicks in" when none of env / answers / .extract provided it.
OUTPUT_FORMAT=$(resolve_auto KISS_OUTPUT_FORMAT "markdown") || true

if [ "${KISS_DRY_RUN:-0}" = "1" ]; then
    # Dry-run: compute the path only, don't mkdir/write.
    OUT_FILE="$KISS_REPO_ROOT/$KISS_DOCS_DIR/_template-output/example.md"
    echo "[dry-run] would write: $OUT_FILE"
    echo "[dry-run] topic:       $TOPIC"
    echo "[dry-run] format:      $OUTPUT_FORMAT"
    exit 0
fi

OUT_DIR=$(worktype_dir "_template-output")
OUT_FILE="$OUT_DIR/example.md"

if ! confirm_before_write "Write example artefact to $OUT_FILE."; then
    echo "Aborted." >&2
    exit 1
fi

cat > "$OUT_FILE" <<EOF
# Example artefact — $TOPIC

This file was generated by \`agent-skills/_template/scripts/bash/example-action.sh\`
as a demonstration of the shared helper library. Real skills produce
real content here — see the template's \`kiss-<name>.md\` prompt for
what a given skill should emit.

- Repo root:        $KISS_REPO_ROOT
- Docs root:        $KISS_DOCS_DIR
- Current feature:  ${KISS_CURRENT_FEATURE:-<none>}
- Output format:    $OUTPUT_FORMAT
EOF

write_extract "$OUT_FILE" \
    "TOPIC=$TOPIC" \
    "OUTPUT_FORMAT=$OUTPUT_FORMAT" > /dev/null

echo "Wrote $OUT_FILE"
